version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
  - github-actions
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
  labels:
  - dependencies
  - python
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  labels:
  - dependencies
  - javascript
- package-ecosystem: cargo
  directory: backend/
  schedule:
    interval: weekly
  labels:
  - dependencies
  - rust
