version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tatsu
    versions:
    - ">= 5.a, < 6"
  - dependency-name: urllib3
    versions:
    - ">= 1.26.a, < 1.27"
  - dependency-name: python-dotenv
    versions:
    - 0.16.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: virtualenv
    versions:
    - 20.4.0
    - 20.4.1
    - 20.4.2
    - 20.4.3
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: soupsieve
    versions:
    - "2.1"
    - "2.2"
  - dependency-name: pillow
    versions:
    - 8.1.0
  - dependency-name: py
    versions:
    - 1.10.0
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - ">= 5.a, < 6"
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: bootstrap-icons
    versions:
    - 1.4.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: "@popperjs/core"
    versions:
    - 2.7.0
    - 2.8.2
    - 2.8.3
    - 2.8.4
    - 2.8.6
    - 2.9.0
    - 2.9.1
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.2
  - dependency-name: "@fullcalendar/timegrid"
    versions:
    - 5.5.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: bootstrap
    versions:
    - 5.0.0-beta2
  - dependency-name: sass-loader
    versions:
    - 10.1.1
