repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.22.0
  hooks:
  - id: eslint
    additional_dependencies:
    - eslint@7.32.0
    - eslint-plugin-vue@7.17.0
    - eslint-plugin-prettier@4.2.1
    args: [--fix]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.7.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
  - id: pretty-format-toml
    exclude: .*.lock
    args: [--autofix]
