repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.23.0'  # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@7.32.0
          - eslint-plugin-vue@7.17.0
        args: [--fix]
  - repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        args: ['--profile', 'black', '--filter-files']
  - repo: https://github.com/psf/black
    rev: '22.6.0'
    hooks:
      - id: black
