repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v9.4.0      # Use the sha / tag you want to point at
  hooks:
  - id: eslint
    additional_dependencies:
    - eslint@7.32.0
    - eslint-plugin-vue@7.17.0
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    exclude: docker-compose.yml|docker-services.yml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    exclude: poetry.lock
    args: [--autofix, --indent, '2']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.9
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
    # - repo: https://github.com/RobertCraigie/pyright-python
    #   rev: v1.1.367
    #   hooks:
    #   - id: pyright
# Tests are temporarily disabled because there are too much error to fix at
# this time.
#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v1.0.1
#  hooks:
#  - id: mypy
#    additional_dependencies: [types-requests, types-setuptools]
