language: python
python: "3.6"     # Currently, the website runs on python 3.6
cache:
    - pip
    - npm

# Databases
services:
    - postgresql
    - redis-server

# Don't build on branch commits; only on master + PRs
branches:
    only:
        - master

# Dependencies
install:
    - pip install -r requirements.txt
    - npm install

# Before tests
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - flask sql init
    - npx webpack --mode production

# Run tests
script:
    - pytest
    - pre-commit run --all-files --show-diff-on-failure
