# Python version that is used in prod
language: python
python: "3.9"

# Cache install data
cache:
    - pip
    - npm

# Databases
services:
    - postgresql
    - redis

# Don't build on branch commits; only on master + PRs
branches:
    only:
        - main

# Nodejs/npm version that is used in prod
before_install:
    - nvm install 10.23.0
    - nvm use 10.23.0

# Dependencies
install:
    - pip install -r dev-requirements.txt
    - npm install

# Before tests
before_script:
    - wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1E8zboqLDRdufXnXZJUrLnSLih_ATaekO" -O api.zip
    - unzip api.zip
    - psql -c 'create database travis_ci_test;' -U postgres
    - flask sql init
    - flask redis update
    - npm run build

# Run tests
script:
    - pre-commit run --all-files --show-diff-on-failure
    - pytest
