# Python version that is used in prod
language: python
python: "3.6"

# Cache install data
cache:
    - pip
    - npm

# Databases
services:
    - postgresql
    - redis

# Don't build on branch commits; only on master + PRs
branches:
    only:
        - master

# Nodejs/npm version that is used in prod
before_install:
    - nvm install 10.22.0
    - nvm use 10.22.0

# Dependencies
install:
    - pip install -r requirements.txt
    - npm install

# Before tests
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - flask sql init
    - npm run build

# Run tests
script:
    - pre-commit run --all-files --show-diff-on-failure
    - pytest
