[dependencies]
chrono = {version = "0.4.24", features = ["serde"]}
pyo3 = {version = "0.16.5", features = ["extension-module"]}
quick-xml = {version = "0.28.2", features = ["serialize"]}
reqwest = {version = "0.11.18", features = ["json"]}
roxmltree = "0.18.0"
serde = {version = "1.0.163", features = ["derive"]}
thiserror = "1.0.40"

[lib]
crate-type = ["cdylib"]
name = "backend"

[package]
edition = "2021"
name = "backend"
version = "0.1.0"

[package.metadata.docs.rs]
all-features = true
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
