[[bin]]
name = "backend"
path = "src/main.rs"

[dependencies]
chrono = {version = "0.4.24", features = ["serde"]}
dotenv = "0.15.0"
quick-xml = {version = "0.28.2", features = ["serialize"]}
reqwest = {version = "0.11.18", features = ["json"]}
rocket = "=0.5.0-rc.3"
serde = {version = "1.0.163", features = ["derive"]}
thiserror = "1.0.40"

[lib]
name = "backend"
path = "src/lib.rs"

[package]
edition = "2021"
name = "backend"
version = "0.1.0"
