[[bin]]
name = "backend"
path = "src/bin.rs"

[dependencies]
chrono = {version = "0.4.24", features = ["serde"]}
pyo3 = {version = "0.16.5", features = ["extension-module"]}
quick-xml = {version = "0.28.2", features = ["serialize"]}
roxmltree = "0.18.0"
serde = {version = "1.0.163", features = ["derive"]}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
name = "backend"

[package]
edition = "2021"
name = "backend"
version = "0.1.0"
