[dependencies]
pyo3 = {version = "0.16.5", features = ["extension-module"]}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
name = "backend"

[package]
edition = "2021"
name = "backend"
version = "0.1.0"
