# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[migrations_directory]
dir = "migrations"

[print_schema]
custom_type_derives = ["diesel::query_builder::QueryId"]
file = "src/schema.rs"
