"""add uuid to schedule

Revision ID: 1c9723cf49c9
Revises: ae91c7ca9560
Create Date: 2020-10-16 21:23:29.819069

"""

import sqlalchemy as sa
from alembic import op

import backend.models as md

# revision identifiers, used by Alembic.
revision = "1c9723cf49c9"
down_revision = "ae91c7ca9560"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedule", sa.Column("last_modified_by", md.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "last_modified_by")
    # ### end Alembic commands ###
