"""track usage rework

Revision ID: 243308ddc5e0
Revises: 78218d17934c
Create Date: 2021-01-07 19:11:46.440884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "243308ddc5e0"
down_revision = "78218d17934c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flask_usage", sa.Column("endpoint", sa.String(length=64), nullable=True)
    )
    op.drop_column("flask_usage", "xforwardedfor")
    op.drop_column("flask_usage", "authorization")
    op.drop_column("flask_usage", "ip_info")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flask_usage",
        sa.Column(
            "ip_info", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "flask_usage",
        sa.Column("authorization", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flask_usage",
        sa.Column(
            "xforwardedfor", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("flask_usage", "endpoint")
    # ### end Alembic commands ###
