"""track usage rework

Revision ID: 300410acb1c7
Revises: 78218d17934c
Create Date: 2021-01-07 20:28:19.226771

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "300410acb1c7"
down_revision = "78218d17934c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flask_usage", sa.Column("endpoint", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "flask_usage", sa.Column("url_args", sa.String(length=512), nullable=True)
    )
    op.drop_column("flask_usage", "ip_info")
    op.drop_column("flask_usage", "xforwardedfor")
    op.drop_column("flask_usage", "authorization")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flask_usage",
        sa.Column("authorization", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flask_usage",
        sa.Column(
            "xforwardedfor", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "flask_usage",
        sa.Column(
            "ip_info", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("flask_usage", "url_args")
    op.drop_column("flask_usage", "endpoint")
    # ### end Alembic commands ###
