"""api usage

Revision ID: 78218d17934c
Revises: c56f06d50437
Create Date: 2020-11-09 20:04:12.430003

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "78218d17934c"
down_revision = "c56f06d50437"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("datetime", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_usage")
    # ### end Alembic commands ###
