"""add unsaved to user

Revision ID: ae91c7ca9560
Revises: 1f13a87097d8
Create Date: 2020-10-15 19:46:27.823662

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ae91c7ca9560"
down_revision = "1f13a87097d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "autosave",
            sa.Boolean(),
            server_default=sa.sql.expression.literal(False),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "autosave")
    # ### end Alembic commands ###
