"""add last schedule column in User

Revision ID: c56f06d50437
Revises: 1c9723cf49c9
Create Date: 2020-10-17 00:03:53.366441

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c56f06d50437"
down_revision = "1c9723cf49c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("last_schedule_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_schedule_id")
    # ### end Alembic commands ###
