"""dev-v1

Revision ID: e1300b949935
Revises:
Create Date: 2020-07-29 16:41:51.250722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1300b949935'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('choice', sa.Integer(), default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'choice')
    # ### end Alembic commands ###
