#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 ADE-Scheduler.
#
# ADE-Scheduler is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

flask sql init
flask redis flush
