# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ADE_AUTHORIZATION: ${{ secrets.ADE_AUTHORIZATION }}
      ADE_DATA: ${{ secrets.ADE_DATA }}
      ADE_DB_PATH: postgresql+psycopg2://adeschtest:adeschtest@localhost:5432/adeschtest
      ADE_FAKE_API: true
      ADE_URL: ${{ secrets.ADE_URL }}
      FLASK_APP: app.py
      FLASK_ENV: production
      FLASK_SALT: any
      FLASK_SECRET_KEY: any
      MAIL_ADMIN: admin@localhost
      MAIL_SERVER: localhost
      MAIL_USERNAME: no-reply@localhost
      UCLOUVAIN_CLIENT_ID: ${{ secrets.UCLOUVAIN_CLIENT_ID }}
      UCLOUVAIN_CLIENT_SECRET: ${{ secrets.UCLOUVAIN_CLIENT_SECRET }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v4

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: poetry

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Docker compose up
      run: docker-compose up -d

    - name: Bootstrap
      run: |
        poetry run ./scripts/bootstrap
        poetry run ./scripts/setup
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1E8zboqLDRdufXnXZJUrLnSLih_ATaekO" -O api.zip
        unzip api.zip

    - name: Test with pytest
      run: |
        poetry run ./run-tests.sh
