# DISABLE TEST REGARDING THIS ISSUE:
# https://github.com/reviewdog/action-languagetool/issues/32
#
#on:
#  pull_request:
#  workflow_dispatch:
#
#name: LanguageTool check
#
#jobs:
#  languagetool_check:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - uses: reviewdog/action-languagetool@v1.14.0
#      with:
#        reporter: github-pr-review
#        patterns: '**/*.md **/*.po **/*.rst **/*.json'
#        level: warning
