# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main, refactor]

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    permissions: write-all
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build docs
      run: cargo doc --lib --no-deps

    - name: Fix index.html problem
      # See: https://dev.to/deciduously/prepare-your-rust-api-docs-for-github-pages-2n5i
      run: |
        rm -rf ./docs
        echo "<meta http-equiv=\"refresh\" content=\"0; url=backend\">" > target/doc/index.html
        cp -r target/doc ./docs

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-pages-artifact@v1
      with:
        path: backend/docs/

    - name: Deploy to GitHub Pages
      id: deployment
      if: github.event_name != 'pull_request'
      uses: actions/deploy-pages@v1
